// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HikCentral.Dispositivos.Models;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }

    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Itemtipoclasificador> Itemtipoclasificadors { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");

        modelBuilder.Entity<Itemtipoclasificador>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("itemtipoclasificador_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Activestatus).HasDefaultValue(0);
        });
        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}