// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HikCentral.Dispositivos.Models;

[Table("itemtipoclasificador")]
[Index("BoPlaceId", Name = "idx00343823")]
[Index("BoOwnerId", Name = "idx00343824")]
public partial class Itemtipoclasificador
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("bo_place_id")]
    public Guid? BoPlaceId { get; set; }

    [Column("bo_owner_id")]
    public Guid? BoOwnerId { get; set; }

    [Column("activestatus")]
    public int? Activestatus { get; set; }

    [Column("codigo")]
    [StringLength(60)]
    public string Codigo { get; set; }

    [Column("nombre")]
    [StringLength(120)]
    public string Nombre { get; set; }

    [Column("placeowner_id")]
    public Guid? PlaceownerId { get; set; }

    [Column("referencia_id")]
    public Guid? ReferenciaId { get; set; }

    [Column("boextension_id")]
    public Guid? BoextensionId { get; set; }

    [Column("bocsf_id")]
    public Guid? BocsfId { get; set; }
}